using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

//Skeleton code generated by Github Copilot AI, Fitted to be used for our case
public class Augments : MonoBehaviour
{
    public Button[] augmentCards;
    public Button rerollButton;

    private List<string> allAugments;
    private List<string> currentChoiceAugments;

    void Start()
    {
        allAugments = new List<string> { "Augment1", "Augment2", "Augment3", "Augment4", "Augment5", "Augment6", "Augment7", "Augment8", "Augment9", "Augment10" };
        currentChoiceAugments = new List<string>();

        rerollButton.onClick.AddListener(Reroll);


        foreach (Button augmentButton in augmentCards)
        {
        augmentButton.onClick.AddListener(() => SelectAugment(augmentButton.GetComponentInChildren<Text>().text));
        }
        
        Reroll();
    }

    void Reroll()
    {
        currentChoiceAugments.Clear();

        //Shuffle the augments
        for(int i = 0; i < allAugments.Count; i++)
        {
            string temp = allAugments[i];
            int randomIndex = Random.Range(i, allAugments.Count);
            allAugments[i] = allAugments[randomIndex];
            allAugments[randomIndex] = temp;
        }

        // Assign the first three augments to the buttons
        for(int i = 0; i < 3; i++)
        {
            currentChoiceAugments.Add(allAugments[i]);
            augmentCards[i].GetComponentInChildren<Text>().text = allAugments[i];
            augmentCards[i].onClick.RemoveAllListeners();
            augmentCards[i].onClick.AddListener(() => SelectAugment(allAugments[i]));
        }
    }

    void SelectAugment(string augment)
    {
        Debug.Log("Select augment: " + augment);
    }
}
